runtime: python37
entrypoint: cd website && gunicorn -b :$PORT website.wsgi:application

handlers:
# This configures Google App Engine to serve the files in the app's
# static directory.
- url: /static
  static_dir: website/landing/static/

# This handler routes all requests not caught above to the main app. 
# It is required when static routes are defined, but can be omitted 
# (along with the entire handlers section) when there are no static 
# files defined.
- url: /.*
  script: auto