version: '3'

services: 
  app:
    build:
      context: ../
      dockerfile: ./docker/app.docker
    image: website:app
    command: python website/manage.py runserver 0.0.0.0:8000
    container_name: website-app
    restart: on-failure
    volumes:
    - ..:/app
    ports:
    - "8000:8000"
