version: '3'

services:
  web:
    build:
      context: ../
      dockerfile: ./docker.production/web.docker
    image: website-prod-web:1.0
    container_name: website-prod-web
    ports:
      - "81:80"
    links:
      - app
    restart: always
  
  app:
    build:
      context: ../
      dockerfile: ./docker.production/app.docker
    image: website-prod-app:1.0
    container_name: website-prod-app
    command: bash -c "cd website && gunicorn --bind=0.0.0.0:8000 website.wsgi:application"
    restart: always
