version: '3'

services:
  web:
    build:
      context: ../
      dockerfile: ./docker.production/web.docker
    image: gcr.io/gioawesomesite/website-prod-web:1.4
    container_name: website-prod-web
    ports:
      - "81:80"
    links:
      - django-service
    restart: always
  
  django-service:
    build:
      context: ../
      dockerfile: ./docker.production/app.docker
    image: gcr.io/gioawesomesite/website-prod-app:1.6
    container_name: website-prod-app
    command: /bin/sh -c "cd website && gunicorn --bind=0.0.0.0:80 website.wsgi:application"
    restart: always
